[project]
name = "fourier-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numba>=0.62.1",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
]
